apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-lb
  namespace: default
  labels:
    component: elasticsearch
    role: load-balancer
spec:
  serviceAccount: elasticsearch
  replicas: 1
  selector:
    component: elasticsearch
    role: load-balancer
  template:
    metadata:
      labels:
        component: elasticsearch
        role: load-balancer
    spec:
      containers:
      - name: elasticsearch-lb
        image: pires/elasticsearch:lb
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
