apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    component: elasticsearch
    role: load-balancer
spec:
  selector:
    component: elasticsearch
    role: load-balancer
  ports:
  - name: http
    port: 9200
    protocol: TCP
