apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-data
  namespace: default
  labels:
    component: elasticsearch
    role: data
spec:
  serviceAccount: elasticsearch
  replicas: 1
  selector:
    component: elasticsearch
    role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - name: elasticsearch-data
        image: pires/elasticsearch:data
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
