apiVersion: v1
kind: ReplicationController
metadata:
  name: es-client
  namespace: default
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: client
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-client
        image: quay.io/pires/docker-elasticsearch-kubernetes:1.7.1-4
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: NAMESPACE
          value: "default"
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
