apiVersion: v1
kind: ReplicationController
metadata:
  name: es-data
  namespace: default
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-data
        image: quay.io/pires/docker-elasticsearch-kubernetes:1.7.1-4
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: NAMESPACE
          value: "default"
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
