apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal: "21186"
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-p9oq3uc1
  labels:
    component: graylog-node
  name: graylog-node
  namespace: default
spec:
  clusterIP: 172.20.255.34
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: apiport
    port: 12900
    protocol: TCP
    targetPort: 12900
  - name: tcpin
    port: 1234
    targetPort: 1234
    protocol: TCP
  selector:
    component: graylog-node
  sessionAffinity: None
  type: LoadBalancer
#status:
#  loadBalancer:
#    ingress:
#    - ip: 172.17.0.16
