apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    component: mongo
spec:
  selector:
    component: mongo
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
    
