id: elasticsearch-data
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    component: elasticsearch
    role: data
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: elasticsearch-data
        containers:
          - name: elasticsearch-data
            image: pires/elasticsearch:data
            ports:
              - name: transport
                containerPort: 9300
            volumeMounts:
              - name: es-persistent-storage
                mountPath: /data
        volumes:
          - name: es-persistent-storage
            source:
              emptyDir: {}
    labels:
      component: elasticsearch
      role: data
